name: mysacco
description: Sky World Limited's Mobile Banking Application

version: 1.0.0+1

environment:
    sdk: ">=2.4.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    provider: ^3.1.0
    carousel_slider:
    direct_select_flutter: ^1.0.4
    cupertino_icons: ^0.1.2
    flutter_masked_text: ^0.8.0
    grouped_buttons: ^1.0.4
    splashscreen: ^1.2.0
    imei_plugin: ^1.1.4
    xml: ^3.5.0
    intl: ^0.16.0
    permission_handler: ^3.2.2
    dio: ^3.0.3
    flutter_html: ^0.11.0
    path_provider: ^1.3.0
    localstorage: ^2.0.0
    reflectable: ^2.1.0
    encrypt: ^3.3.1
    showcaseview: ^0.1.3
    xpath: ^0.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: any
    build_runner: any

flutter:
    uses-material-design: true

    assets:
        - assets/home/org_logo.png
        - assets/home/drawer_paper.jpg
        - assets/icons/avatars/current_user.png
        - assets/icons/result_states/success.png
        - assets/icons/result_states/warning.png
        - assets/icons/result_states/error.png
        - assets/icons/result_states/question.png

    fonts:
        -   family: IBMPlexSansRegular
            fonts:
                -   asset: assets/fonts/IBMPlexSans-Regular.ttf
        -   family: IBMPlexSansMedium
            fonts:
                -   asset: assets/fonts/IBMPlexSans-Medium.ttf
        -   family: IBMPlexSansSemiBold
            fonts:
                -   asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        -   family:  FeatherIcons
            fonts:
                -   asset: assets/fonts/FeatherIcons.ttf